name: Execute Scheduled Posts

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  execute-posts:
    runs-on: ubuntu-latest
    steps:
      - name: Call Vercel API
        run: |
          response=$(curl -s -w "\n%{http_code}" -X POST \
            "${{ secrets.VERCEL_URL }}/api/execute-scheduled-posts" \
            -H "Authorization: Bearer ${{ secrets.CRON_SECRET }}" \
            -H "Content-Type: application/json")
          
          http_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | head -n -1)
          
          echo "HTTP Code: $http_code"
          echo "Response: $body"
          
          if [ "$http_code" -ne 200 ]; then
            echo "Error executing scheduled posts"
            exit 1
          fi